Patient("", "", "", Coordinate(listOf(16.47 - 90.0f, 96.10 - 90.0f)), "co-burma14-1"), listOf()),
Patient("", "", "", Coordinate(listOf(16.47 - 90.0f, 94.44 - 90.0f)), "co-burma14-2"), listOf()),
Patient("", "", "", Coordinate(listOf(20.09 - 90.0f, 92.54 - 90.0f)), "co-burma14-3"), listOf()),
Patient("", "", "", Coordinate(listOf(22.39 - 90.0f, 93.37 - 90.0f)), "co-burma14-4"), listOf()),
Patient("", "", "", Coordinate(listOf(25.23 - 90.0f, 97.24 - 90.0f)), "co-burma14-5"), listOf()),
Patient("", "", "", Coordinate(listOf(22.00 - 90.0f, 96.05 - 90.0f)), "co-burma14-6"), listOf()),
Patient("", "", "", Coordinate(listOf(20.47 - 90.0f, 97.02 - 90.0f)), "co-burma14-7"), listOf()),
Patient("", "", "", Coordinate(listOf(17.20 - 90.0f, 96.29 - 90.0f)), "co-burma14-8"), listOf()),
Patient("", "", "", Coordinate(listOf(16.30 - 90.0f, 97.38 - 90.0f)), "co-burma14-9"), listOf()),
Patient("", "", "", Coordinate(listOf(14.05 - 90.0f, 98.12 - 90.0f)), "co-burma14-10"), listOf()),
Patient("", "", "", Coordinate(listOf(16.53 - 90.0f, 97.38 - 90.0f)), "co-burma14-11"), listOf()),
Patient("", "", "", Coordinate(listOf(21.52 - 90.0f, 95.59 - 90.0f)), "co-burma14-12"), listOf()),
Patient("", "", "", Coordinate(listOf(19.41 - 90.0f, 97.13 - 90.0f)), "co-burma14-13"), listOf()),
Patient("", "", "", Coordinate(listOf(20.09 - 90.0f, 94.55 - 90.0f)), "co-burma14-14"), listOf()),




